(ns net.wikipunk.rdf.lv2.ev
  "A port-based real-time generic event interface."
  {:rdf/type :owl/Ontology,
   :owl/deprecated true,
   :vann/preferredNamespacePrefix "ev",
   :rdfs/seeAlso
     #:rdf{:uri
             "https://gitlab.com/lv2/lv2/-/raw/master/lv2/event.lv2/event.meta.ttl"},
   :dcat/downloadURL
     "https://gitlab.com/lv2/lv2/-/raw/master/lv2/event.lv2/event.ttl",
   :owl/imports #:rdf{:uri "http://lv2plug.in/ns/lv2core"},
   :rdf/about [#:rdf{:uri "http://lv2plug.in/ns/ext/event"}],
   :vann/preferredNamespaceUri "http://lv2plug.in/ns/ext/event#",
   :rdf/ns-prefix-map {"ev" "http://lv2plug.in/ns/ext/event#",
                       "lv2" "http://lv2plug.in/ns/lv2core#",
                       "rdfs" "http://www.w3.org/2000/01/rdf-schema#",
                       "owl" "http://www.w3.org/2002/07/owl#",
                       "rdf" "http://www.w3.org/1999/02/22-rdf-syntax-ns#"}}
  (:refer-clojure :exclude []))

(def Event
  "A single generic time-stamped event."
  {:rdfs/comment "A single generic time-stamped event.",
   :rdfs/label "Event",
   :rdf/type :rdfs/Class})

(def EventPort
  "An LV2 event port."
  {:rdfs/comment "An LV2 event port.",
   :rdfs/subClassOf :lv2/Port,
   :rdfs/label "Event Port",
   :rdf/type :rdfs/Class})

(def FrameStamp
  "The default time stamp unit for an event."
  {:rdfs/comment "The default time stamp unit for an event.",
   :rdfs/label "Audio Frame Time Stamp",
   :rdfs/subClassOf :ev/TimeStamp,
   :rdf/type :rdfs/Class})

(def TimeStamp
  "The time stamp of an Event."
  {:rdfs/comment "The time stamp of an Event.",
   :rdfs/label "Event Time Stamp",
   :rdf/type :rdfs/Class})

(def generatesTimeStamp
  "A time stamp type generated by this input port."
  {:rdfs/comment "A time stamp type generated by this input port.",
   :rdfs/label "generates time stamp type",
   :rdfs/range :rdfs/Class,
   :rdfs/domain [:lv2/OutputPort :ev/EventPort],
   :rdf/type [:owl/ObjectProperty :rdf/Property]})

(def generic
  "Port works with generic events."
  {:rdfs/comment "Port works with generic events.",
   :rdfs/label "generic event port",
   :rdf/type :lv2/PortProperty})

(def inheritsEvent
  "Output port inherits event types from an input port."
  {:rdfs/comment "Output port inherits event types from an input port.",
   :rdfs/label "inherits event type",
   :rdfs/range :lv2/Port,
   :rdfs/domain [:lv2/OutputPort :ev/EventPort],
   :rdf/type [:owl/ObjectProperty :rdf/Property]})

(def inheritsTimeStamp
  "Output port inherits time stamp types from an input port."
  {:rdfs/comment "Output port inherits time stamp types from an input port.",
   :rdfs/label "inherits time stamp type",
   :rdfs/range :lv2/Port,
   :rdfs/domain [:lv2/OutputPort :ev/EventPort],
   :rdf/type [:owl/ObjectProperty :rdf/Property]})

(def supportsEvent
  "An event type supported by this port."
  {:rdfs/comment "An event type supported by this port.",
   :rdfs/label "supports event type",
   :rdfs/range :rdfs/Class,
   :rdfs/domain :ev/EventPort,
   :rdf/type [:owl/ObjectProperty :rdf/Property]})

(def supportsTimeStamp
  "A time stamp type supported by this input port."
  {:rdfs/comment "A time stamp type supported by this input port.",
   :rdfs/label "supports time stamp type",
   :rdfs/range :rdfs/Class,
   :rdfs/domain [:lv2/InputPort :ev/EventPort],
   :rdf/type [:owl/ObjectProperty :rdf/Property]})