(ns net.wikipunk.rdf.lv2.ev
  "http://lv2plug.in/ns/ext/event#"
  {:dcat/downloadURL
   "https://gitlab.com/lv2/lv2/-/raw/master/lv2/event.lv2/event.ttl",
   :owl/deprecated true,
   :owl/imports {:rdf/uri "http://lv2plug.in/ns/lv2core"},
   :rdf/about {:rdf/uri "http://lv2plug.in/ns/ext/event"},
   :rdf/ns-prefix-map {"ev"   "http://lv2plug.in/ns/ext/event#",
                       "lv2"  "http://lv2plug.in/ns/lv2core#",
                       "owl"  "http://www.w3.org/2002/07/owl#",
                       "rdf"  "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
                       "rdfs" "http://www.w3.org/2000/01/rdf-schema#"},
   :rdf/type :owl/Ontology,
   :rdfs/label "LV2 Event",
   :rdfs/seeAlso
   {:rdf/uri
    "https://gitlab.com/lv2/lv2/-/raw/master/lv2/event.lv2/event.meta.ttl"},
   :vann/preferredNamespacePrefix "ev",
   :vann/preferredNamespaceUri "http://lv2plug.in/ns/ext/event#"})

(def Event
  "A single generic time-stamped event."
  {:rdf/about  :ev/Event,
   :rdf/type   :rdfs/Class,
   :rdfs/label "Event"})

(def EventPort
  "An LV2 event port."
  {:rdf/about       :ev/EventPort,
   :rdf/type        :rdfs/Class,
   :rdfs/label      "Event Port",
   :rdfs/subClassOf :lv2/Port})

(def FrameStamp
  "The default time stamp unit for an event."
  {:rdf/about       :ev/FrameStamp,
   :rdf/type        :rdfs/Class,
   :rdfs/label      "Audio Frame Time Stamp",
   :rdfs/subClassOf :ev/TimeStamp})

(def TimeStamp
  "The time stamp of an Event."
  {:rdf/about  :ev/TimeStamp,
   :rdf/type   :rdfs/Class,
   :rdfs/label "Event Time Stamp"})

(def generatesTimeStamp
  "A time stamp type generated by this input port."
  {:rdf/about   :ev/generatesTimeStamp,
   :rdf/type    [:owl/ObjectProperty :rdf/Property],
   :rdfs/domain [:lv2/OutputPort :ev/EventPort],
   :rdfs/label  "generates time stamp type",
   :rdfs/range  :rdfs/Class})

(def generic
  "Port works with generic events."
  {:rdf/about  :ev/generic,
   :rdf/type   :lv2/PortProperty,
   :rdfs/label "generic event port"})

(def inheritsEvent
  "Output port inherits event types from an input port."
  {:rdf/about   :ev/inheritsEvent,
   :rdf/type    [:owl/ObjectProperty :rdf/Property],
   :rdfs/domain [:lv2/OutputPort :ev/EventPort],
   :rdfs/label  "inherits event type",
   :rdfs/range  :lv2/Port})

(def inheritsTimeStamp
  "Output port inherits time stamp types from an input port."
  {:rdf/about   :ev/inheritsTimeStamp,
   :rdf/type    [:owl/ObjectProperty :rdf/Property],
   :rdfs/domain [:lv2/OutputPort :ev/EventPort],
   :rdfs/label  "inherits time stamp type",
   :rdfs/range  :lv2/Port})

(def supportsEvent
  "An event type supported by this port."
  {:rdf/about   :ev/supportsEvent,
   :rdf/type    [:owl/ObjectProperty :rdf/Property],
   :rdfs/domain :ev/EventPort,
   :rdfs/label  "supports event type",
   :rdfs/range  :rdfs/Class})

(def supportsTimeStamp
  "A time stamp type supported by this input port."
  {:rdf/about   :ev/supportsTimeStamp,
   :rdf/type    [:owl/ObjectProperty :rdf/Property],
   :rdfs/domain [:lv2/InputPort :ev/EventPort],
   :rdfs/label  "supports time stamp type",
   :rdfs/range  :rdfs/Class})